Repository FRCTeam2910/Common, pull requests merged in 2020-01, with the labels that each got.

#77 Deprecate Old Code And Update Subsystem Manager
  examples/swerve-robot/src/main/java/frc/swerverobot/Robot.java
  examples/swerve-robot/src/main/java/frc/swerverobot/subsystems/DrivetrainSubsystem.java
  robot/src/main/java/org/frcteam2910/common/robot/UpdateManager.java
  robot/src/main/java/org/frcteam2910/common/robot/commands/ArcadeDriveCommand.java
  robot/src/main/java/org/frcteam2910/common/robot/commands/CheesyDriveCommand.java
  robot/src/main/java/org/frcteam2910/common/robot/commands/HolonomicDriveCommand.java
  robot/src/main/java/org/frcteam2910/common/robot/commands/SetDrivetrainGearCommand.java
  robot/src/main/java/org/frcteam2910/common/robot/commands/ZeroFieldOrientedCommand.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/Drivetrain.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/HolonomicDrivetrain.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/ShiftingTankDrivetrain.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/Subsystem.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/SubsystemManager.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/SwerveDrivetrain.java
  robot/src/main/java/org/frcteam2910/common/robot/subsystems/TankDrivetrain.java
Labels: Priority: Low, Ready for Review

#78 Update WPILib to 2020
  build.gradle
  examples/swerve-robot/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  robot/build.gradle
  robot/vendordeps/Phoenix.json
  robot/vendordeps/REVRobotics.json
  robot/vendordeps/WPILibNewCommands.json
  robot/vendordeps/WPILibOldCommands.json
  robot/vendordeps/navx_frc.json
  settings.gradle
Labels: Build System, Priority: High

#75 Add SDS Mk2 swerve module builder
  examples/swerve-robot/src/main/java/frc/swerverobot/subsystems/DrivetrainSubsystem.java
  robot/src/main/java/org/frcteam2910/common/robot/drivers/Mk2SwerveModuleBuilder.java
Labels: Feature, Priority: High

#72 Trajectory rewrite
  build.gradle
  examples/trajectory-generation/build.gradle
  examples/trajectory-generation/src/main/java/org/frcteam2910/common/examples/trajectory_generation/Main.java
  settings.gradle
  src/main/java/org/frcteam2910/common/control/CentripetalAccelerationConstraint.java
  src/main/java/org/frcteam2910/common/control/FeedforwardConstraint.java
  src/main/java/org/frcteam2910/common/control/HolonomicMotionProfiledTrajectoryFollower.java
  src/main/java/org/frcteam2910/common/control/HolonomicPurePursuitTrajectoryFollower.java
  src/main/java/org/frcteam2910/common/control/ITrajectoryConstraint.java
  src/main/java/org/frcteam2910/common/control/MaxAccelerationConstraint.java
  src/main/java/org/frcteam2910/common/control/MaxVelocityConstraint.java
  src/main/java/org/frcteam2910/common/control/Path.java
  src/main/java/org/frcteam2910/common/control/PathArcSegment.java
  src/main/java/org/frcteam2910/common/control/PathGenerator.java
  src/main/java/org/frcteam2910/common/control/PathLineSegment.java
  src/main/java/org/frcteam2910/common/control/PathSegment.java
  src/main/java/org/frcteam2910/common/control/PurePursuitTrajectoryFollowerBase.java
  src/main/java/org/frcteam2910/common/control/SimplePathBuilder.java
  src/main/java/org/frcteam2910/common/control/SplinePathBuilder.java
  src/main/java/org/frcteam2910/common/control/SplinePathGenerator.java
  src/main/java/org/frcteam2910/common/control/SplinePathSegment.java
  src/main/java/org/frcteam2910/common/control/Trajectory.java
  src/main/java/org/frcteam2910/common/control/TrajectoryConstraint.java
  src/main/java/org/frcteam2910/common/control/Waypoint.java
  src/main/java/org/frcteam2910/common/io/PathReader.java
  src/main/java/org/frcteam2910/common/io/PathWriter.java
  src/main/java/org/frcteam2910/common/io/json/InterpolatingDoubleJsonHandler.java
  src/main/java/org/frcteam2910/common/io/json/PathSegmentJsonHandler.java
  src/main/java/org/frcteam2910/common/io/json/Rotation2JsonHandler.java
  src/main/java/org/frcteam2910/common/io/json/SimpleMatrixJsonHandler.java
  src/main/java/org/frcteam2910/common/math/spline/BezierSplineHelper.java
  src/main/java/org/frcteam2910/common/math/spline/CubicBezierSpline.java
  src/main/java/org/frcteam2910/common/math/spline/CubicHermiteSpline.java
  src/main/java/org/frcteam2910/common/math/spline/HermiteSpline.java
  src/main/java/org/frcteam2910/common/math/spline/HermiteSplineHelper.java
  src/main/java/org/frcteam2910/common/math/spline/QuinticBezierSpline.java
  src/main/java/org/frcteam2910/common/math/spline/Spline.java
  src/main/java/org/frcteam2910/common/math/spline/SplineHelper.java
  src/main/java/org/frcteam2910/common/motion/MotionProfile.java
  src/main/java/org/frcteam2910/common/motion/TrapezoidalMotionProfile.java
  src/test/java/org/frcteam2910/common/control/CentripetalAccelerationConstraintTest.java
  src/test/java/org/frcteam2910/common/control/FeedforwardConstraintTest.java
  src/test/java/org/frcteam2910/common/control/MaxAccelerationConstraintTest.java
  src/test/java/org/frcteam2910/common/control/PathArcSegmentTest.java
  src/test/java/org/frcteam2910/common/control/PathLineSegmentTest.java
  src/test/java/org/frcteam2910/common/control/PurePursuitTrajectoryFollowerBaseTest.java
  src/test/java/org/frcteam2910/common/control/SplinePathGeneratorTest.java
  src/test/java/org/frcteam2910/common/control/TrajectoryTest.java
  src/test/java/org/frcteam2910/common/io/PathIoTests.java
  src/test/java/org/frcteam2910/common/math/spline/BezierSplineHelperTest.java
  src/test/java/org/frcteam2910/common/math/spline/CubicBezierSplineTest.java
  src/test/java/org/frcteam2910/common/math/spline/CubicHermiteSplineTest.java
  src/test/java/org/frcteam2910/common/math/spline/HermiteSplineTest.java
  src/test/java/org/frcteam2910/common/math/spline/SplineHelperTest.java
  src/test/java/org/frcteam2910/common/math/spline/SplineTest.java
  src/test/resources/org/frcteam2910/common/io/example_path.json
Labels: Feature

#89 Add support for Falcon 500 motors as angle motors for the Mk2 builder
  robot/src/main/java/org/frcteam2910/common/robot/drivers/Mk2SwerveModuleBuilder.java
  robot/vendordeps/Phoenix.json
Labels: Priority: High
